### ISSUE TITLE
xmpp auth error.

### ISSUE THREAD

**Issue by aplsms** [lhost/sendxmpp#13]
Hi, i have error connecting to the openfire xmpp server.
username, password and jserver are correct.
XML-Stream-1.24
Net-XMPP-1.05

$ echo "This is a test IM" | sendxmpp -t -n -u "apetrenko"  release@conference.jabber.corp.company.com  -j jabber.corp.company.com -v 
sendxmpp: config: 'username' => 'apetrenko@corp.company.com'
sendxmpp: config: 'jserver' => 'jabber.corp.company.com'
sendxmpp: config: 'password' => 'password'
sendxmpp: ssl_verify: 0
sendxmpp: tls_ca_path:
sendxmpp: Connect: 1
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1829.
Use of uninitialized value $sid in concatenation (.) or string at /Library/Perl/5.18/XML/Stream.pm line 2735.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 2737.
Use of uninitialized value $sid in concatenation (.) or string at /Library/Perl/5.18/XML/Stream.pm line 1668.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1669.
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/XML/Stream.pm line 1669.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1671.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1673.
Use of uninitialized value in numeric eq (==) at /Library/Perl/5.18/XML/Stream.pm line 1673.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1675.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1678.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 2615.
Use of uninitialized value $sid in concatenation (.) or string at /Library/Perl/5.18/XML/Stream.pm line 2735.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 2737.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 440.
Use of uninitialized value in hash element at /Library/Perl/5.18/Net/XMPP/Connection.pm line 433.
Use of uninitialized value in string eq at /usr/local/bin/sendxmpp line 518.
Error 'AuthSend': [?]
Use of uninitialized value $sid in concatenation (.) or string at /Library/Perl/5.18/XML/Stream.pm line 1668.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1669.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1671.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1673.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1264.
Use of uninitialized value in string eq at /Library/Perl/5.18/XML/Stream.pm line 1264.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1264.
Use of uninitialized value in string eq at /Library/Perl/5.18/XML/Stream.pm line 1264.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1267.
Use of uninitialized value in delete at /Library/Perl/5.18/XML/Stream.pm line 1267.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1268.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1270.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1270.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1270.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1270.
Use of uninitialized value $sid in hash element at /Library/Perl/5.18/XML/Stream.pm line 1270.
Use of uninitialized value $sid in delete at /Library/Perl/5.18/XML/Stream.pm line 1272.
sendxmpp: Disconnect

**Comment by lhost** [comment]
Looks like a problem with SSL. Try --ssl, --no-tls-verify, --tls-ca-path option and try again.

**Comment by aplsms** [comment]
Checked with all option combinations: there is no success,

**Comment by eribertomota** [comment]
You need install the CA certificate in client side. See #29
