### ISSUE TITLE
Sendxmpp can not connect to ipv6 servers.

### ISSUE THREAD

**Issue by tigusoft-vm** [lhost/sendxmpp#17]
Sendxmpp can not connect to ipv6 servers.

in v1.24
echo aaa | ./sendxmpp rfree-d@meshnet.pl
Could not connect to 'h.im.meshnet.pl' on port 5222: HASH(0x1af6048)

in v1.23-1.1 (debian stable)
echo aaa | sendxmpp rfree-d@meshnet.pl
sendxmpp error: Could not connect to 'h.im.meshnet.pl' on port 5222: IO::Socket::INET: Bad hostname 'h.im.meshnet.pl'

cat ~/.sendxmpprc 
myuser@h.im.meshnet.pl mypassword myuser@meshnet.pl

$ !ping6
ping6 h.im.meshnet.pl
64 bytes from c.l: icmp_seq=1 ttl=42 time=1.90 ms

$dig -t ANY h.im.meshnet.pl | egrep -v '^\;' 

h.im.meshnet.pl.        3246    IN      AAAA    fc5f:c567:102:c14e:326e:5035:d7e5:9f78

**Comment by lhost** [comment]
https://www.perl.org/about/whitepapers/perl-ipv6.html

sendxmpp doesn't use IO::Socket::INET directly, so this looks like a Net::XMPP::Client issue

**Comment by lhost** [comment]
cherry-picked in aaba858c4198a4995254a51ea7f8814fa13e2ae5
