### ISSUE TITLE
Remove "I<>" from manpage

### ISSUE THREAD

**Issue by andrey-utkin** [lhost/sendxmpp#23]
Hi, and thanks for awesome software!

Currently I have net-im/sendxmpp-1.24 installed in my Gentoo. Config example in manpage looks this way:

```
CONFIGURATION FILE
       You may define a '~/.sendxmpprc' file with the necessary data for your xmpp-account. Since version 1.24 the following format is supported:

           username: I<your_username>
           jserver: I<jabber_server>
           port: I<jabber_port>
           password: I<your_jabber_password>
           component: I<optional_component_name>

       Example for Google Talk servers:

           username: I<lubomir.host>
           jserver: I<talk.google.com>
           password: I<my-secure-password>
           component: I<gmail.com>

```

This `I<>` stuff seems serving purpose of formatting, but it doesn't really work. It comes at a cost because I lost some time trying with config file actually having those symbols.

**Comment by micha137** [comment]
You have to read the manpage with man, not as plain Text.

**Comment by lhost** [comment]
You shuld read documentation with this command:
```bash
perldoc ./sendxmpp
```
But you are right - markers `I<>` doesn't work. I remove these markers from configuration example (other places are OK). Commited, pushed. Thanks for your report.
