### ISSUE TITLE
work with openfire

### ISSUE THREAD

**Issue by Krong** [lhost/sendxmpp#3]
Hello!
I tested sendxmpp with openfire in kubuntu, fedora and centos.
I works in kubuntu only.
In fedora and centos the error is "Error 'AuthSend': error: not-authorized[?]"

In debug mode the only difference is:
In kubuntu:
XMPP::Conn: AuthSASL: shiney new auth
XML::Stream: Send: ... mechanism='PLAIN'
In fedora and centos:
XMPP::Conn: AuthSASL: shiney new auth
XML::Stream: Send: ....' mechanism='DIGEST-MD5'

It seems that openfire do not understand sendxmpp's DIGEST-MD5 authentication.

So questions are: 
- we have the same script and the same jabber server but in kubuntu PLAIN mechanism and in fedora/centos DIGEST-MD5 ?
- how to say sendxmpp to use PLAIN always? 
- is any patch or option to work with openfire with DIGEST-MD5?

Thanks!

**Comment by lhost** [comment]
It seems to be a bug of Net::XMPP perl module.

**Comment by easyyu** [comment]
What about this error?
I run in same problem.
Is there any kind of solution after 3 years?
