### ISSUE TITLE
Wrong server name used when `--jserver` given

### ISSUE THREAD

**Issue by cweiske** [lhost/sendxmpp#6]
I've got an account `cweiske@company.com`, the XMPP server is running on `xmpp.company.com`. The XMPP SRV record for `company.com` links to `xmpp.company.com`.

Now when specifying `--jserver=xmpp.company.com`, this host name is not only used to connect to, but also as xmpp target server. I get the following error:

Request:

```
<?xml version='1.0'?>
<stream:stream version='1.0' xmlns:stream='http://etherx.jabber.org/streams' 
 xmlns='jabber:client'
 to='xmpp.company.com'
 from='cyberdyne'
 xml:lang='en' >
```

Response:

```
<stream:error>
  <host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>
  <text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>
    This server does not serve xmpp.company.com
  </text>
</stream:error>
```

The `xmpp.company.com` hostname should only be used for connecting, not as general xmpp server hostname.

This is with sendxmpp 1.22-1 (ubuntu) and libnet-xmpp-perl 1.02-3.

**Comment by uvok** [comment]
Please reopen?

my config file says

    username: me@myhost
    jserver: localhost
    password: mypassword

where myhost is the external server name, but I connect via localhost

sendxmpp says

    sendxmpp: config: 'jserver' => 'localhost'
    sendxmpp: config: 'username' => 'me@myhost'
    sendxmpp: config: 'password' => 'mypassword'
    sendxmpp: ssl_verify: 1
    sendxmpp: tls_ca_path: 
    Could not connect to 'localhost' on port 5222: HASH(0xaf6e38)

But my prosody server says 

    Sep 25 22:13:28 c2s1710100	info	Client connected
    Sep 25 22:13:28 c2s1710100	info	c2s stream for <127.0.0.1> closed: This server does not serve localhost
    Sep 25 22:13:28 c2s1710100	info	Client disconnected: connection closed

So although I specified the host in my username, it seems to replace it with the jserver

**Comment by lhost** [comment]
Please, try the following config and try again:

username: me@localhost
jserver: myhost
password: mypassword

**Comment by lhost** [comment]
Please, try the following config and try again:

username: me
jserver: localhost
component: myhost
password: mypassword

**Comment by uvok** [comment]
@lhost Thanks, that works
